### ISSUE TITLE
Null pointer exception 

### ISSUE THREAD

**Issue by MTGrimm** [CMPUT301W24T07/Quick-scanneR#113]
![image](https://github.com/CMPUT301W24T07/Quick-scanneR/assets/98679259/dfe20db3-af05-4c4b-81ed-184557c3ef6f)

This seems to be happening whenever I pull a new update and try to run it for the first time. After trying to launch the app again it seems to work fine though. Not quite an urgent issue since it doesn't hinder working on the rest of the app really but probably something we should figure out before we hand this in

**Comment by jalmeida89** [comment]
after way too much work, done
