### ISSUE TITLE
Events pagination

### ISSUE THREAD

**Issue by DylanD03** [CMPUT301W24T07/Quick-scanneR#87]
Currently loads 30 events sorted by time, from firebaseEventController

-- GetEvents() gets the first 30
-- ContinueGetEvents() Gets the next 30 

Change our list to grab the next 30 when we scroll further down / click load more?

**Comment by DylanD03** [comment]
i'm working on this one later

**Comment by jalmeida89** [comment]
with current event lists, honestly dont think trying for pagination is needed anymore, as changing everything to not be live updates to allow for this would be alot lol.

**Comment by jalmeida89** [comment]
not doing
