### ISSUE TITLE
Empty list Views

### ISSUE THREAD

**Issue by DylanD03** [CMPUT301W24T07/Quick-scanneR#99]
Maybe add a generic text to any empty list views to show that it's empty, rather than displaying a blank screen.

Example: "You are not organizing any events!"

**Comment by DylanD03** [comment]
This is just something extra for all of us to do, if we have the time.

**Comment by jalmeida89** [comment]
added this to a couple lists (signed up and checked in lists), ill add to the rest later if i got time
